In [2]:
docs = [
  {

      "id" : 1,
      "body" : "The star in our solar system provides heat and light."

  },
  {

      "id" : 2,
      "body" : "That Hollywood star walked the red carpet for the movie premiere."

  },
  {

      "id" : 3,
      "body" : "Astronomers observe distant stars and galaxies using telescopes."

  }
]



In [3]:
from sys import version_info
import argparse
import json
import matplotlib.pyplot as plt
import os
import sys
sys.path.append(os.path.abspath(r'C:\Users\srksr\NLP\NLP_project\NLP_ASSIGNMENT2'))
from sentenceSegmentation import SentenceSegmentation
from tokenization import Tokenization
from inflectionReduction import InflectionReduction
from stopwordRemoval import StopwordRemoval
from informationRetrieval import InformationRetrieval
from evaluation import Evaluation


In [4]:
tokenizer = Tokenization()
sentSeg = SentenceSegmentation()
inflRed = InflectionReduction()
stopwordRem = StopwordRemoval()
ir = InformationRetrieval()
eval = Evaluation()

In [5]:
docids = [doc["id"] for doc in docs]
segmentedDocs = []
for doc in docs:
    segmentedDoc = sentSeg.punkt(doc["body"])
    segmentedDocs.append(segmentedDoc)


tokenizedDocs = []
for doc in segmentedDocs:
    tokenizedDoc = tokenizer.spacyTokenizer(doc)
    tokenizedDocs.append(tokenizedDoc)


reducedDocs = []
for doc in tokenizedDocs:
    reducedDoc = inflRed.reduce(doc)
    reducedDocs.append(reducedDoc)

stop_words=["the", "in", "our", "and", "that", "for"]
stopwordRemovedDocs = []
for doc in reducedDocs:
    stopwordRemovedDoc = stopwordRem.fromList(doc, stop_words)
    stopwordRemovedDocs.append(stopwordRemovedDoc)



In [6]:
stopwordRemovedDocs

[[['star', 'solar', 'system', 'provid', 'heat', 'light', '.']],
 [['hollywood', 'star', 'walk', 'red', 'carpet', 'movi', 'premier', '.']],
 [['astronom', 'observ', 'distant', 'star', 'galaxi', 'use', 'telescop', '.']]]

In [7]:
ir.buildIndex(stopwordRemovedDocs,docids)
ir.index

{'star': {1: 1, 2: 1, 3: 1, 'idf': 0.0},
 'solar': {1: 1, 'idf': 1.0986122886681098},
 'system': {1: 1, 'idf': 1.0986122886681098},
 'provid': {1: 1, 'idf': 1.0986122886681098},
 'heat': {1: 1, 'idf': 1.0986122886681098},
 'light': {1: 1, 'idf': 1.0986122886681098},
 '.': {1: 1, 2: 1, 3: 1, 'idf': 0.0},
 'hollywood': {2: 1, 'idf': 1.0986122886681098},
 'walk': {2: 1, 'idf': 1.0986122886681098},
 'red': {2: 1, 'idf': 1.0986122886681098},
 'carpet': {2: 1, 'idf': 1.0986122886681098},
 'movi': {2: 1, 'idf': 1.0986122886681098},
 'premier': {2: 1, 'idf': 1.0986122886681098},
 'astronom': {3: 1, 'idf': 1.0986122886681098},
 'observ': {3: 1, 'idf': 1.0986122886681098},
 'distant': {3: 1, 'idf': 1.0986122886681098},
 'galaxi': {3: 1, 'idf': 1.0986122886681098},
 'use': {3: 1, 'idf': 1.0986122886681098},
 'telescop': {3: 1, 'idf': 1.0986122886681098}}

In [8]:
import numpy as np
tf_matrix = np.zeros_like(ir.tfidf).T
for i in range(len(ir.words)):
    for j in range(ir.total_docs):
        if ir.words[i] in ir.index and docids[j] in ir.index[ir.words[i]]:
            tf_matrix[i][j] = ir.index[ir.words[i]][docids[j]]

In [9]:
tf_matrix

array([[1., 1., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 1., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [10]:

for i in range(len(ir.words)):
    print(ir.words[i], ":", tf_matrix[i])

star : [1. 1. 1.]
solar : [1. 0. 0.]
system : [1. 0. 0.]
provid : [1. 0. 0.]
heat : [1. 0. 0.]
light : [1. 0. 0.]
. : [1. 1. 1.]
hollywood : [0. 1. 0.]
walk : [0. 1. 0.]
red : [0. 1. 0.]
carpet : [0. 1. 0.]
movi : [0. 1. 0.]
premier : [0. 1. 0.]
astronom : [0. 0. 1.]
observ : [0. 0. 1.]
distant : [0. 0. 1.]
galaxi : [0. 0. 1.]
use : [0. 0. 1.]
telescop : [0. 0. 1.]


In [11]:
for key in ir.index:
    print(key, ":", ir.index[key]['idf'])

star : 0.0
solar : 1.0986122886681098
system : 1.0986122886681098
provid : 1.0986122886681098
heat : 1.0986122886681098
light : 1.0986122886681098
. : 0.0
hollywood : 1.0986122886681098
walk : 1.0986122886681098
red : 1.0986122886681098
carpet : 1.0986122886681098
movi : 1.0986122886681098
premier : 1.0986122886681098
astronom : 1.0986122886681098
observ : 1.0986122886681098
distant : 1.0986122886681098
galaxi : 1.0986122886681098
use : 1.0986122886681098
telescop : 1.0986122886681098


In [12]:
for i in range(3):
    print(docids[i], ":", '\t'.join(map(str, ir.tfidf[i].round(3))))

1 : 0.0	1.099	1.099	1.099	1.099	1.099	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
2 : 0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.099	1.099	1.099	1.099	1.099	1.099	0.0	0.0	0.0	0.0	0.0	0.0
3 : 0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.099	1.099	1.099	1.099	1.099	1.099


In [13]:
query = ["slip-flow heat transfer in internal channels"]
processedQuery = stopwordRem.fromList(inflRed.reduce(tokenizer.spacyTokenizer(query)), stop_words)
print(processedQuery)


doc_list = {}
for words in processedQuery:
    for word in words:
        if word in list(ir.index.keys()):
            doc_list[word] = list(ir.index[word].keys())
            doc_list[word].remove('idf')
print(doc_list)

[['slip', '-', 'flow', 'heat', 'transfer', 'intern', 'channel']]
{'heat': [1]}


In [14]:
querytfidf = np.zeros((1, len(ir.words)))
for i in range(len(ir.words)):
    if ir.words[i] in processedQuery[0]:
        querytfidf[0][i] += ir.index[ir.words[i]]['idf']

In [15]:
querytfidf

array([[0.        , 0.        , 0.        , 0.        , 1.09861229,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [16]:
normalisedQuery = querytfidf / np.linalg.norm(querytfidf)
normalisedtfidf_docs = ir.normalized_tfidf
similarity_scores = np.dot(normalisedtfidf_docs, normalisedQuery.T).flatten()
similarity_scores

array([0.4472136, 0.       , 0.       ])

In [17]:
[docids[j] for j in np.argsort(-similarity_scores)]

[1, 2, 3]